/// Flutter icons TeneIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TeneIcon
///      fonts:
///       - asset: fonts/TeneIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TeneIcon {
  TeneIcon._();

  static const _kFontFam = 'TeneIcon';

  static const IconData setting = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData passcode = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData license = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData repeat = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData support = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData about = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData crypto_card___currency = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData currency = const IconData(0xe80c, fontFamily: _kFontFam);
}
